install.packages("readr")
options(repos = c(CRAN = "https://cran.r-project.org"))
install.packages(c("readr","ggplot2","tidyr"))
options(repos = c(CRAN = "https://cran.r-project.org"))
install.packages(c("readr","ggplot2","tidyr","shiny"))
